# Generated by Django 4.2.30 on 2026-07-09 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotApiJob',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('status', models.TextField(default='pending')),
                ('mode', models.TextField()),
                ('file_url', models.TextField()),
                ('language', models.TextField(default='ru-RU')),
                ('translate_to', models.TextField(blank=True, default='')),
                ('custom_prompt', models.TextField(blank=True, default='')),
                ('duration_sec', models.FloatField(blank=True, null=True)),
                ('result_text', models.TextField(blank=True, null=True)),
                ('result_analysis', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'api_jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BotApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('key_hash', models.TextField()),
                ('name', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_keys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BotSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('minutes_total', models.IntegerField()),
                ('minutes_used', models.FloatField()),
                ('stars_paid', models.IntegerField()),
                ('telegram_charge_id', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'subscriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('trial_used', models.BooleanField(default=False)),
                ('star_balance', models.IntegerField(default=0)),
                ('free_minutes', models.FloatField(default=0)),
                ('email', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebTinkoffOrder',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(default='topup', max_length=20)),
                ('amount_rub', models.IntegerField()),
                ('tinkoff_payment_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('web_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tinkoff_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Веб-заказ T-Bank',
                'verbose_name_plural': 'Веб-заказы T-Bank',
                'db_table': 'web_tinkoff_orders',
            },
        ),
    ]
